### ISSUE TITLE
infernal demon

### ISSUE THREAD

**Issue by Demente231** [Open-Games-Community/Custom-Server-13.11#10]
el piso de lava de infernal esta bug por q todo mundo se para ensima para matar alos infernal sin q ningun monster los pueda atacar a los player

**Comment by Alexv45** [comment]
Hola,

Efectivamente, las lavas eran distintas, se ha corregido el error.

![212](https://github.com/Open-Games-Community/Custom-Server-13.11/assets/89811188/8c503c12-4730-4bf9-a518-c91605a5f89e)
