### ISSUE TITLE
[ Assassin Class ] Pet & Familiar Bug

### ISSUE THREAD

**Issue by Nazgul001** [Open-Games-Community/Custom-Server-13.11#15]
[ Familiar ] Al querer sumonearlo gasta la mana mas no lo aparece.
[ Pet ] Al usar el comando para summonear el Pet muestra dialogo "Unable to create the pet"

![imagen_2023-07-25_014428682](https://github.com/Open-Games-Community/Custom-Server-13.11/assets/6056264/3832251a-c645-4ed0-842d-dd72cc52c206)

**Comment by Alexv45** [comment]
> [ Familiar ] Al querer sumonearlo gasta la mana mas no lo aparece. [ Pet ] Al usar el comando para summonear el Pet muestra dialogo "Unable to create the pet"
> 
> ![imagen_2023-07-25_014428682](https://user-images.githubusercontent.com/6056264/255827621-3832251a-c645-4ed0-842d-dd72cc52c206.png)

Puedes Relogear y probar ?
No consigo reproducir el error.

Has aparecido directamente en Thais con una vocation Elegida, o has subido nivel en Dawnport y salido eligiendo tu Vocation ?.

El personaje es nivel 100 minimo ?

**Comment by Alexv45** [comment]
Solucionado, el problema era un archivo modificado.
