### ISSUE TITLE
[ Assassin Class ] Reward Wall Bug

### ISSUE THREAD

**Issue by Nazgul001** [Open-Games-Community/Custom-Server-13.11#16]
Al querer selecionar los items de la reward wall, esta no los muestra por lo tanto no lo puede reclamar.

![Reward Wall](https://github.com/Open-Games-Community/Custom-Server-13.11/assets/6056264/45de6dba-4c64-437b-947a-28ad70946e6b)

**Comment by Alexv45** [comment]
> Al querer selecionar los items de la reward wall, esta no los muestra por lo tanto no lo puede reclamar.
> 
> ![Reward Wall](https://user-images.githubusercontent.com/6056264/255828528-45de6dba-4c64-437b-947a-28ad70946e6b.png)

![image](https://github.com/Open-Games-Community/Custom-Server-13.11/assets/89811188/50d04009-ac31-479a-8de4-a81abe202bb6)

Puedes probar de relogear haber si no seria el mismo problema que en los servidores 12x, al llegar en el continente para tener el Prey, etc habia que reloguear.

**Comment by Alexv45** [comment]
Solucionado, el problema era un archivo modificado.
