### ISSUE TITLE
Mount & Outfit Coins

### ISSUE THREAD

**Issue by Nazgul001** [Open-Games-Community/Custom-Server-13.11#17]
No estan sirviendo solo dice que no se puede usar el objeto

**Comment by Alexv45** [comment]
Hola ,
Leer con atención el update v1.1.0 en la parte actualización de la descarga del servidor. Estas últimas también han sido notificadas en el Discord.
https://opengamescommunity.com/index.php?resources/13-11-endless-rl-custom-v1-1-0.852/updates
