### ISSUE TITLE
miboss 

### ISSUE THREAD

**Issue by Demente231** [Open-Games-Community/Custom-Server-13.11#5]
cuando vas a matar a king zelos en vez de mandarte a los mini boss te manda directo al kin zelos
otra cosa los mini boss de las ciudades como thais darashia edron y libreria las puertas no dejan pasar y al cambiar las puertas se q da igual de cerradas

**Comment by Alexv45** [comment]
> cuando vas a matar a king zelos en vez de mandarte a los mini boss te manda directo al kin zelos otra cosa los mini boss de las ciudades como thais darashia edron y libreria las puertas no dejan pasar y al cambiar las puertas se q da igual de cerradas

Las puertas de los Mini Bosses han sido liberadas.
La Storage UID ha sido correctamente agregada a la puerta de acceso al King Zelos, para que únicamente puedan acceder los que hayan previamente matado 5 o más mini bosses.
