### ISSUE TITLE
boss puertas e items de addons y mounts 

### ISSUE THREAD

**Issue by Demente231** [Open-Games-Community/Custom-Server-13.11#6]
31970, 32325, 10 estas cordenadas son de un boss q no funciona 
32963, 32297, 8 varias puertas no abren y 32963, 32312, 8 hay un teleport q no te lleva a ningun lado
32697, 32234, 8 no abre una puerta y no jala un tp
32682, 32292, 8 un teleport q no te lleva a ningun lado 
32672, 31543, 9 esta puerta no abre
32688, 31543, 9 la puerta te manda a un lugar en vez de abrir y salir 
You own no premium account, lack the base outfit or already own this outfit part. esto dicen la malloria de los items q dan outfind y mount pero no te los da por mas q tengas premium

**Comment by Alexv45** [comment]
> 31970, 32325, 10 estas cordenadas son de un boss q no funciona 32963, 32297, 8 varias puertas no abren y 32963, 32312, 8 hay un teleport q no te lleva a ningun lado 32697, 32234, 8 no abre una puerta y no jala un tp 32682, 32292, 8 un teleport q no te lleva a ningun lado 32672, 31543, 9 esta puerta no abre 32688, 31543, 9 la puerta te manda a un lugar en vez de abrir y salir You own no premium account, lack the base outfit or already own this outfit part. esto dicen la malloria de los items q dan outfind y mount pero no te los da por mas q tengas premium

Brain Head Agregado , con sus respectivos summons. Corregido en `#ac15b47`
Posiciones liberadas / Furious Scorpion agregado con Reward Chest. Corregido en `#ac15b47`
Puertas Corregidas, y puerta TP corregida para arbir y cerrar. Corregido en `#ac15b47`

Para agregar Addons a cada jugador, necessitan de antemano tener el Outfit de Base, este último se obtiene mediante Bosses.
