### ISSUE TITLE
player dont dead. just after reconect

### ISSUE THREAD

**Issue by Peeedroferreira** [Open-Games-Community/Custom-Server-13.11#7]
the player's life resets and he doesn't die only after he relogs in the character

**Comment by Alexv45** [comment]
> the player's life resets and he doesn't die only after he relogs in the character

Hello,

Can you send a video or gif about this ?
We didn't not understand exactly what you mean ?

Die
![image](https://user-images.githubusercontent.com/89811188/236220776-9dad9adc-21ac-46bc-bcdf-5e4b86f8605d.png)
Relog
![image](https://user-images.githubusercontent.com/89811188/236220832-78331288-1bd1-4427-9752-4cf16735a411.png)
