### ISSUE TITLE
boss

### ISSUE THREAD

**Issue by Demente231** [Open-Games-Community/Custom-Server-13.11#9]
33618, 32950, 15 este tp te deberia de llevar a esta zona 33609, 32963, 15 
33616, 32964, 15 y esta palanca a un boss q es como un rotword con cristales ensima me parece

**Comment by Alexv45** [comment]
> 33618, 32950, 15 este tp te deberia de llevar a esta zona 33609, 32963, 15 33616, 32964, 15 y esta palanca a un boss q es como un rotword con cristales ensima me parece

Posiciones corregidas, boss agregado en su zona correspondiente.
